learning_log/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('learning_logs.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
from django.urls import include, path

from rest_framework import routers

from .views import (
    IndexView,
    TagListView,
    TagCreateView,
    EntryListView,
    EntryNewestListView,
    EntryTopListView,
    EntryTagListView,
    EntryCreateView,
    EntryDetailView,
    EntryLikeView,
    EntryUpdateView,
    EntryDeleteView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView
)

from learning_logs import views

router = routers.DefaultRouter()
router.register(r'tags', views.TagViewSet)

app_name = 'learning_logs'

urlpatterns = [
    path('api-tag/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', IndexView.as_view(), name='index'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tag/add/', TagCreateView.as_view(), name='tag_create'),
    path('entries/', EntryListView.as_view(), name='entries'),
    path('new/', EntryNewestListView.as_view(), name='newest'),
    path('top/', EntryTopListView.as_view(), name='top'),
    path('tag/<slug:slug>/', EntryTagListView.as_view(), name='tag'),
    path('entry/add/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/<slug:slug>/', EntryDetailView.as_view(), name='entry'),
    path('entry/<slug:slug>/like/', EntryLikeView.as_view(), name='entry_like'),
    path('entry/<slug:slug>/update/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='entry_delete'),
    path('entry/<slug:slug>/comment/add/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

users/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    RegisterView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView
)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileDetailView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('delete/', ProfileDeleteView.as_view(), name='profile_delete'),
]

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models
# from django.utils.text import slugify
from pytils.translit import slugify
from django.urls import reverse


class Tag(models.Model):
    PRIMARY = 'primary'
    SECONDARY = 'secondary'
    SUCCESS = 'success'
    INFO = 'info'
    WARNING = 'warning'
    DANGER = 'danger'
    LIGHT = 'light'
    DARK = 'dark'
    COLOR_CHOICES = (
        (PRIMARY, 'Blue'),
        (SECONDARY, 'Gray'),
        (SUCCESS, 'Green'),
        (INFO, 'Cyan'),
        (WARNING, 'Yellow'),
        (DANGER, 'Red'),
        (LIGHT, 'White'),
        (DARK, 'Black')
    )
    color = models.CharField(max_length=10, choices=COLOR_CHOICES, default=PRIMARY)
    title = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Entry(models.Model):
    tag = models.ManyToManyField(Tag, default='', blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='entry')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='learning_logs/img', default='', blank=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Entry, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'entries'
        ordering = ['title']

    def __str__(self):
        return self.title

    def text_short(self):
        if len(self.text) < 100:
            return self.text
        else:
            return self.text[:100] + '...'

    def get_absolute_url(self):
        return reverse('learning_logs:entry', kwargs={'slug': self.slug})


class LogLikedEntries(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    is_liked = models.BooleanField(default=False)

    def __str__(self):
        return self.owner.username + ' ' + self.entry.title


class LogViewedEntries(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    remote_addr = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment')
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        if len(self.text) < 40:
            return self.text
        else:
            return self.text[:40] + '...'

    def get_absolute_url(self):
        return reverse('learning_logs:entry', kwargs={'slug': self.entry.slug})

learning_logs/forms.py
from django import forms

from .models import Tag, Entry, Comment


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ['title', 'color']
        labels = {
            'title': '',
            'color': '',
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter tag name'
            }),
            'color': forms.Select(attrs={
                'class': 'form-control',
            })
        }


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = [
            'tag',
            'title', 
            'text',
            'image',
        ]
        labels = {
            'title': 'Header',
            'text': 'Text',
            'image': 'Photo',
            'tag': 'Tags'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',   
                'placeholder': 'Enter header'
            }),
            'text': forms.Textarea(attrs={
                'cols': 40,
                'class': 'form-control', 
                'placeholder': 'Enter text article'
            }),
            'tag': forms.SelectMultiple(attrs={
                'class': 'form-select',
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
            })
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        labels = {
            'text': 'Leave a Comment:'
        }

        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 5,
                'class': 'form-control',
                'placeholder': 'Enter your comment...'
            })
        }

learning_logs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import RedirectView, TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormMixin, FormView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy

from rest_framework import viewsets
from rest_framework import permissions

from users.models import Person

from learning_logs.models import Tag, Entry, Comment, LogLikedEntries, LogViewedEntries
from learning_logs.serializers import TagSerializer
from learning_logs.forms import TagForm, EntryForm, CommentForm


class TagViewSet(viewsets.ModelViewSet):
    queryset = Tag.objects.all().order_by('slug')
    serializer_class = TagSerializer
    permission_classes = [permissions.IsAuthenticated]


class MyUserPassesTestMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        owner = self.get_queryset()[0].owner
        return self.request.user == owner


class IndexView(ListView):
    queryset = Entry.objects.all()[:3]
    context_object_name = 'entries'
    template_name = 'learning_logs/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        return context


class TagListView(ListView):
    model = Tag
    context_object_name = 'tags'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Tags'
        return context


class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('learning_logs:tags')
    success_message = "%(title)s was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add new tag'
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title = self.object.title
        )


class EntryListView(ListView):
    paginate_by = 1

    def get_queryset(self):
        self.entry_list = Entry.objects.all()
        self.question = self.request.GET.get('q')
        if self.question:
            self.entry_list = self.entry_list.filter(
                Q(title__icontains=self.question)|
                Q(text__icontains=self.question)
            ).order_by('-date_added')

        return self.entry_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.question:
            context['last_question'] = '?q=%s' % self.question
        
        context['q'] = self.question
        context['title'] = 'Articles'
        return context


class EntryNewestListView(ListView):
    paginate_by = 1
    queryset = Entry.objects.order_by('-date_added')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'New Articles'
        return context


class EntryTopListView(ListView):
    paginate_by = 1
    queryset = Entry.objects.order_by('-likes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Top Articles'
        return context
    

class EntryTagListView(ListView):
    paginate_by = 1

    def get_queryset(self):
        self.entry_list = Entry.objects.filter(tag__slug=self.kwargs['slug'])
        return self.entry_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Tag: {}'.format(self.kwargs['slug'].title()) 
        return context


class EntryDetailView(DetailView):
    model = Entry
    context_object_name = 'entry'
    form_class = CommentForm

    def dispatch(self, *args, **kwargs):
        self.entry = get_object_or_404(Entry, slug=self.kwargs['slug'])
        self.remote_addr = self.request.META['REMOTE_ADDR']
        obj, created = LogViewedEntries.objects.get_or_create(
            entry=self.entry,
            remote_addr=self.remote_addr
        )
        if created:
            self.entry.views += 1
            self.entry.save()
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class
        context['tags'] = self.get_object().tag.all()
        context['comments'] = self.get_object().comment_set.all()
        context['title'] = self.get_object().title
        return context


class EntryLikeView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        self.entry = get_object_or_404(Entry, slug=self.kwargs['slug'])
        obj = LogLikedEntries.objects.get_or_create(
            owner=self.request.user,
            entry=self.entry
        )[0]
        if not obj.is_liked:
            obj.is_liked = True
            self.entry.likes += 1
            messages.success(self.request, "Added to Liked entry")
        else:
            obj.is_liked = False
            self.entry.likes -= 1
            messages.success(self.request, "Revoke to Liked entry")

        obj.save()
        self.entry.save()
        return reverse('learning_logs:entry', kwargs={'slug': self.kwargs['slug']})


class EntryCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Entry
    form_class = EntryForm
    success_message = "%(title)s was created successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title = self.object.title,
        )

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add article'
        return context


class EntryUpdateView(MyUserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Entry
    form_class = EntryForm
    success_message = "%(title)s was updated successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title = self.object.title,
        )

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update article'
        return context


class EntryDeleteView(UserPassesTestMixin, RedirectView):

    def get_queryset(self):
        return get_object_or_404(Entry, pk=self.kwargs['pk'])

    def test_func(self):
        return self.request.user == self.get_queryset().owner

    def post(self, request, *args, **kwargs):
        self.get_queryset().delete()
        messages.success(self.request, 'Entry was deleted successfully')
        return super().post(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse('users:profile')


class CommentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Comment
    form_class = CommentForm
    success_message = "Comment was created successfully"

    def get_queryset(self):
        self.entry = get_object_or_404(Entry, slug=self.kwargs['slug'])
        return self.entry

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entry'] = self.get_queryset()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        entry = self.get_queryset()
        form.instance.entry = entry
        entry.comments += 1
        entry.save()
        return super().form_valid(form)


class CommentUpdateView(MyUserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    success_message = "Comment was updated successfully"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Updata comment'
        return context


class CommentDeleteView(UserPassesTestMixin, RedirectView):

    # Get comment for deleting
    def get_comment(self):
        return get_object_or_404(Comment, pk=self.kwargs['pk'])
    
    # Check comment owner
    def test_func(self):
        return self.request.user == self.get_comment().owner
    
    # Deleting comment
    def post(self, request, *args, **kwargs):
        entry = self.get_comment().entry
        entry.comments -= 1
        entry.save()
        self.get_comment().delete()
        messages.success(self.request, 'Comment was deleted successfully')
        return super().post(request, *args, **kwargs)

    # Redirect to profile
    def get_redirect_url(self, *args, **kwargs):
        return reverse('users:profile')

learning_logs/templates/learning_logs/comment_form.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'learning_logs:entries' %}">Articles</a></li>
<li class="breadcrumb-item"><a href="{% url 'learning_logs:entry' comment.entry.slug %}">{{ comment.entry }}</a></li>
{% endblock%}

{% block content %}
<section class="container">
  <div class="row">
    <div class="col-12">
      <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Update comment</button>
      </form>
    </div>
  </div>
</section>
<br>
{% endblock %}

learning_logs/templates/learning_logs/entry_detail.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'learning_logs:entries' %}">Articles</a></li>
{% endblock %}

{% block content %}
  <section class="container">
    <div class="row">
      <article class="col-12">

        <!-- Display author entry -->
        <section class="row">
          <div class="col-1">
            {% if entry.owner.person.image %}
              <img class="rounded" style="width:50px;height:50px;" src="{{ entry.owner.person.image.url }}">
            {% else %}
              <img class="rounded" style="width:50px;height:50px;" src="{% static 'img/avatar-tiny.jpg' %}">
            {% endif %}
          </div>
          <div class="col-11">
            <spen>{{ entry.owner|capfirst }}</spen><br>
            <span>Pablished on {{ entry.date_added|date:'F d, Y' }}</span>
          </div>
        </section>
        <br>
        
        <!-- Display title block -->
        <h1>
          {{ entry.title }}
          {% if request.user == entry.owner %}
            <a href="{% url 'learning_logs:entry_update' entry.slug %}" class="btn btn-sm btn-outline-warning">Update</a>
            <button class="btn btn-outline-danger btn-sm" type="button" data-toggle="modal" data-target="#entryDelete">Delete</button>
          {% endif %}
        </h1>
        <div id="entryDelete" class="modal fade">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Deleting Entry</h4>
                <button class="close" type="button" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                Do you want to delete a entry {{ entry.title }}
              </div>
              <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
                <form action="{% url 'learning_logs:entry_delete' entry.pk %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-danger" button="submit">Delete</button>
                </form>
              </div>
            </div>
          </div>
        </div>
                
        {# <p>{{ entry.views }} view{{ entry.views|pluralize }}</p> #}

        <!-- Display image -->
        {% if entry.image %}
          <img src="{{ entry.image.url }}" alt="{{ entry.title }}" class="rounded" style="height:300px;">
        {% endif %}

        <!-- Display entry text -->
        <p>{{ entry.text|linebreaks }}</p>
      
        <!-- Display tags -->
        {% for tag in tags %}
          <a href="{% url 'learning_logs:entries' %}?tag_query={{ tag.slug }}" class="btn btn-sm btn-outline-{{ tag.color }}">{{ tag.title }}</a>
        {% endfor %}

        <br><br>

        <!-- Like button -->
        <a href="{% url 'learning_logs:entry_like' entry.slug %}" class="btn btn-outline-info btn-sm">
          Like | {{ entry.likes }}
        </a>

        <br><br>

        <!-- Add new comments -->
        {% if request.user.is_authenticated %}
          <form action="{% url 'learning_logs:comment_create' entry.slug %}" method="post" class="form">
            {% csrf_token %}
            <div class="form-group">
              {{ form }}
            </div>
            <button class="btn btn-outline-success" type="submit">Post comment</button>
          </form>
        {% endif %}

        <br>
      
        <p>{{ entry.comments }} Comment{{ entry.comments|pluralize }}:</p>
        
        <!-- Display comments -->
        {% for comment in comments %}
          <article class="row">
            <div class="col-1">
              {% if comment.owner.person.image %}
                <img class="rounded" style="width:80px;height:80px;" src="{{ comment.owner.person.image.url }}">
              {% else %}
                <img class="rounded" style="width:80px;height:80px;" src="{% static 'img/avatar-tiny.jpg' %}">
              {% endif %}
            </div>
            <div class="col-11">
              <h5>
                <span>{{ comment.owner|capfirst }}</span>&nbsp;
                {% if comment.owner == request.user %}
                  <a href="{% url 'learning_logs:comment_update' comment.pk %}" class="btn btn-outline-warning btn-sm">Update</a>
                  <button class="btn btn-outline-danger btn-sm" type="button" data-toggle="modal" data-target="#commentDelete{{ forloop.counter }}">
                    Delete
                  </button>
                  <div id="commentDelete{{ forloop.counter }}" class="modal fade">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Deleting Comment</h4>
                          <button class="close" type="button" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                          Do you want to delete a comment: {{ comment.text }}
                        </div>
                        <div class="modal-footer">
                          <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
                          <form action="{% url 'learning_logs:comment_delete' comment.pk %}" method="post">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit">Delete</button>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div><!-- /.modal -->
                {% endif %}
              </h5>
              <span>Pablished on {{ comment.date_added|date:'F d, Y' }}</span>
              <p>{{ comment.text|linebreaks }}</p>
            </div>
          </article>
          <br>
        {% empty %}
          <div class="card border-dark mb-3">
              <div class="card-body">
                This article has no comments.
              </div>
          </div>
        {% endfor %}
      </article>
    </div> <!-- end row -->
  </section>
{% endblock %}

learning_logs/templates/learning_logs/entry_form.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'learning_logs:entries' %}">Articles</a></li>
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-header">
        New article
    </div>
    <div class="card-body">
      <form action="" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          {{ form.title.label_tag }}
          {{ form.title }}
          {{ form.title.errors }}
        </div>
        <div class="mb-3">
          {{ form.tag.label_tag }}<br>
          <a id="addTagBtn" class="btn btn-success btn-sm my-3" href="{% url 'learning_logs:tag_create' %}" target="_blank">Add tag</a>
          {{ form.tag }}
          {{ form.tag.errors }}
        </div>
        <div class="mb-3">
          {{ form.text.label_tag }}
          {{ form.text }}
          {{ form.text.errors }}
        </div>
        <div class="mb-3">
          {{ form.image.label_tag }}
          {{ form.image }}
          {{ form.image.errors }}
        </div>
        <button class="btn btn-outline-success" type="submit">{{ title }}</button>
      </form>
    </div>
  </div>

<!-- Modal -->
<div class="modal fade" id="addTagModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create tag</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="addTagForm">
          <div class="mb-3">
            <input type="text" id="tagTitleField" name="title" class="form-control" placeholder="Tag name">
          </div>
          <div class="mb-3">
            <select class="form-select" id="tagColorField" name="color" aria-label="Default select example">
              <option selected>Open this select menu</option>
            </select>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="addTagActionBtn">Save changes</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

learning_logs/templates/learning_logs/entry_list.html
{% extends 'base.html' %}

{% block content %}
  <section class="container">
      {% for entry in entry_list %}
        <div class="card mb-3">
            <div class="card-header">
                <span class="text-muted">{{ entry.date_added|date:'F d, Y' }} by {{ entry.owner|title }}</span>
            </div>
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'learning_logs:entry' entry.slug %}" class="text-dark">{{ entry.title }}</a></h4>
                {% for tag in entry.tag.all %}
                    <span class="badge badge-{{ tag.color }}">{{ tag.title }}</span>&nbsp;
                {% endfor %}
                <p class="card-text">{{ entry.text|linebreaks|truncatewords:50 }}</p>
            </div>
            <div class="card-footer">
                <span>views: {{ entry.views }}&nbsp;&nbsp;</span>
                <span>comments: {{ entry.comments }}&nbsp;&nbsp;</span>
                <span>likes: {{ entry.likes }}&nbsp;&nbsp;</span>
            </div>
        </div>
      {% endfor %}
  </section><!-- container -->
  
  <div class="container">
  {% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                    &laquo;
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
        {% endif %}
        
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link">{{ i }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                    &raquo;
                </a>
            </li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
        {% endif %}
    </ul>
  {% endif %}
  </div><!-- /.container -->
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container btn-light p-5">
        <h1 class="display-3">Live Journal</h1>
        <p class="lead">{% lorem 30 w %}</p>
        <p>
            <a class="btn btn-primary btn-lg" href="{% url 'users:register' %}">
                Register &raquo;
            </a>
        </p>
    </div>
    <div class="container">
        <div class="row">
        {% for entry in entries %}
            <div class="col-md-4">
                <h2>{{ entry.title }}</h2>
                <p>{{ entry.text|truncatewords:50 }}</p>
                <p>
                    <a class="btn btn-secondary" href="{% url 'learning_logs:entry' entry.slug %}">
                        View details &raquo;
                    </a>
                </p>
            </div>
        {% endfor %}
        </div><!-- /.row -->
        <hr>
    </div><!-- /.container -->
</main>
{% endblock %}

learning_logs/templates/learning_logs/tag_form.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'learning_logs:tags' %}">Tags</a></li>
{% endblock %}

{% block content %}
  <section class="container mb-3">
    <div class="row">
      <div class="col-12">
        <form action="" method="post" class="form">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-success" type="submit">Create tag</button>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

learning_logs/templates/learning_logs/tag_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="container">
    <div class="row">
      <div class="col">
        <h2 class="text-info">Tags list</h2>
        {% for tag in tags %}
          <a href="{% url 'learning_logs:tag' tag.slug %}" class="btn btn-sm btn-outline-{{tag.color}}">{{ tag.title }}</a>&nbsp;
        {% empty %}
          <div class="alert alert-primary" role="alert">
            No tags
          </div>
        {% endfor %}
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <a href="{% url 'learning_logs:tag_create' %}" class="btn btn-primary">Add tag</a>
      </div>
    </div>
  </section>
{% endblock %}