learning_log/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('learning_logs.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
from django.urls import include, path

from rest_framework import routers

from .views import (
    IndexView,
    TagListView,
    TagCreateView,
    EntryListView,
    EntryNewestListView,
    EntryTopListView,
    EntryTagListView,
    EntryCreateView,
    EntryDetailView,
    EntryLikeView,
    EntryUpdateView,
    EntryDeleteView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView
)

from learning_logs import views

router = routers.DefaultRouter()
router.register(r'tags', views.TagViewSet)

app_name = 'learning_logs'

urlpatterns = [
    path('api-tag/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', IndexView.as_view(), name='index'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tag/add/', TagCreateView.as_view(), name='tag_create'),
    path('entries/', EntryListView.as_view(), name='entries'),
    path('new/', EntryNewestListView.as_view(), name='newest'),
    path('top/', EntryTopListView.as_view(), name='top'),
    path('tag/<slug:slug>/', EntryTagListView.as_view(), name='tag'),
    path('entry/add/', EntryCreateView.as_view(), name='entry_create'),
    path('entry/<slug:slug>/', EntryDetailView.as_view(), name='entry'),
    path('entry/<slug:slug>/like/', EntryLikeView.as_view(), name='entry_like'),
    path('entry/<slug:slug>/update/', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='entry_delete'),
    path('entry/<slug:slug>/comment/add/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

users/urls.py
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    RegisterView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView
)

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileDetailView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('delete/', ProfileDeleteView.as_view(), name='profile_delete'),
]

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models
# from django.utils.text import slugify
from pytils.translit import slugify
from django.urls import reverse


class Tag(models.Model):
    PRIMARY = 'primary'
    SECONDARY = 'secondary'
    SUCCESS = 'success'
    INFO = 'info'
    WARNING = 'warning'
    DANGER = 'danger'
    LIGHT = 'light'
    DARK = 'dark'
    COLOR_CHOICES = (
        (PRIMARY, 'Blue'),
        (SECONDARY, 'Gray'),
        (SUCCESS, 'Green'),
        (INFO, 'Cyan'),
        (WARNING, 'Yellow'),
        (DANGER, 'Red'),
        (LIGHT, 'White'),
        (DARK, 'Black')
    )
    color = models.CharField(max_length=10, choices=COLOR_CHOICES, default=PRIMARY)
    title = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Entry(models.Model):
    tag = models.ManyToManyField(Tag, default='', blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='entry')
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='learning_logs/img', default='', blank=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Entry, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'entries'
        ordering = ['title']

    def __str__(self):
        return self.title

    def text_short(self):
        if len(self.text) < 100:
            return self.text
        else:
            return self.text[:100] + '...'

    def get_absolute_url(self):
        return reverse('learning_logs:entry', kwargs={'slug': self.slug})


class LogLikedEntries(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    is_liked = models.BooleanField(default=False)

    def __str__(self):
        return self.owner.username + ' ' + self.entry.title


class LogViewedEntries(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    remote_addr = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment')
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        if len(self.text) < 40:
            return self.text
        else:
            return self.text[:40] + '...'

    def get_absolute_url(self):
        return reverse('learning_logs:entry', kwargs={'slug': self.entry.slug})

learning_logs/forms.py
from django import forms

from .models import Tag, Entry, Comment


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ['title', 'color']
        labels = {
            'title': '',
            'color': '',
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter tag name'
            }),
            'color': forms.Select(attrs={
                'class': 'form-control',
            })
        }


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = [
            'tag',
            'title', 
            'text',
            'image',
        ]
        labels = {
            'title': 'Header',
            'text': 'Text',
            'image': 'Photo',
            'tag': 'Tags'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',   
                'placeholder': 'Enter header'
            }),
            'text': forms.Textarea(attrs={
                'cols': 40,
                'class': 'form-control', 
                'placeholder': 'Enter text article'
            }),
            'tag': forms.SelectMultiple(attrs={
                'class': 'form-select',
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control',
            })
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        labels = {
            'text': 'Leave a Comment:'
        }

        widgets = {
            'text': forms.Textarea(attrs={
                'rows': 5,
                'class': 'form-control',
                'placeholder': 'Enter your comment...'
            })
        }

learning_logs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import RedirectView, TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormMixin, FormView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy

from rest_framework import viewsets
from rest_framework import permissions

from users.models import Person

from learning_logs.models import Tag, Entry, Comment, LogLikedEntries, LogViewedEntries
from learning_logs.serializers import TagSerializer
from learning_logs.forms import TagForm, EntryForm, CommentForm


class TagViewSet(viewsets.ModelViewSet):
    queryset = Tag.objects.all().order_by('slug')
    serializer_class = TagSerializer
    permission_classes = [permissions.IsAuthenticated]


class MyUserPassesTestMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        owner = self.get_queryset()[0].owner
        return self.request.user == owner


class IndexView(ListView):
    queryset = Entry.objects.all()[:3]
    context_object_name = 'entries'
    template_name = 'learning_logs/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        return context


class TagListView(ListView):
    model = Tag
    context_object_name = 'tags'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Tags'
        return context


class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('learning_logs:tags')
    success_message = "%(title)s was created successfully"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add new tag'
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title = self.object.title
        )


class EntryListView(ListView):
    paginate_by = 1

    def get_queryset(self):
        self.entry_list = Entry.objects.all()
        self.question = self.request.GET.get('q')
        if self.question:
            self.entry_list = self.entry_list.filter(
                Q(title__icontains=self.question)|
                Q(text__icontains=self.question)
            ).order_by('-date_added')

        return self.entry_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.question:
            context['last_question'] = '?q=%s' % self.question
        
        context['q'] = self.question
        context['title'] = 'Articles'
        return context


class EntryNewestListView(ListView):
    paginate_by = 1
    queryset = Entry.objects.order_by('-date_added')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'New Articles'
        return context


class EntryTopListView(ListView):
    paginate_by = 1
    queryset = Entry.objects.order_by('-likes')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Top Articles'
        return context
    

class EntryTagListView(ListView):
    paginate_by = 1

    def get_queryset(self):
        self.entry_list = Entry.objects.filter(tag__slug=self.kwargs['slug'])
        return self.entry_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Tag: {}'.format(self.kwargs['slug'].title()) 
        return context


class EntryDetailView(DetailView):
    model = Entry
    context_object_name = 'entry'
    form_class = CommentForm

    def dispatch(self, *args, **kwargs):
        self.entry = get_object_or_404(Entry, slug=self.kwargs['slug'])
        self.remote_addr = self.request.META['REMOTE_ADDR']
        obj, created = LogViewedEntries.objects.get_or_create(
            entry=self.entry,
            remote_addr=self.remote_addr
        )
        if created:
            self.entry.views += 1
            self.entry.save()
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class
        context['tags'] = self.get_object().tag.all()
        context['comments'] = self.get_object().comment_set.all()
        context['title'] = self.get_object().title
        return context


class EntryLikeView(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        self.entry = get_object_or_404(Entry, slug=self.kwargs['slug'])
        obj = LogLikedEntries.objects.get_or_create(
            owner=self.request.user,
            entry=self.entry
        )[0]
        if not obj.is_liked:
            obj.is_liked = True
            self.entry.likes += 1
            messages.success(self.request, "Added to Liked entry")
        else:
            obj.is_liked = False
            self.entry.likes -= 1
            messages.success(self.request, "Revoke to Liked entry")

        obj.save()
        self.entry.save()
        return reverse('learning_logs:entry', kwargs={'slug': self.kwargs['slug']})


class EntryCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Entry
    form_class = EntryForm
    success_message = "%(title)s was created successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title = self.object.title,
        )

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add article'
        return context


class EntryUpdateView(MyUserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Entry
    form_class = EntryForm
    success_message = "%(title)s was updated successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            title = self.object.title,
        )

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update article'
        return context


class EntryDeleteView(UserPassesTestMixin, RedirectView):

    def get_queryset(self):
        return get_object_or_404(Entry, pk=self.kwargs['pk'])

    def test_func(self):
        return self.request.user == self.get_queryset().owner

    def post(self, request, *args, **kwargs):
        self.get_queryset().delete()
        messages.success(self.request, 'Entry was deleted successfully')
        return super().post(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse('users:profile')


class CommentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Comment
    form_class = CommentForm
    success_message = "Comment was created successfully"

    def get_queryset(self):
        self.entry = get_object_or_404(Entry, slug=self.kwargs['slug'])
        return self.entry

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entry'] = self.get_queryset()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        entry = self.get_queryset()
        form.instance.entry = entry
        entry.comments += 1
        entry.save()
        return super().form_valid(form)


class CommentUpdateView(MyUserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    success_message = "Comment was updated successfully"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Updata comment'
        return context


class CommentDeleteView(UserPassesTestMixin, RedirectView):

    # Get comment for deleting
    def get_comment(self):
        return get_object_or_404(Comment, pk=self.kwargs['pk'])
    
    # Check comment owner
    def test_func(self):
        return self.request.user == self.get_comment().owner
    
    # Deleting comment
    def post(self, request, *args, **kwargs):
        entry = self.get_comment().entry
        entry.comments -= 1
        entry.save()
        self.get_comment().delete()
        messages.success(self.request, 'Comment was deleted successfully')
        return super().post(request, *args, **kwargs)

    # Redirect to profile
    def get_redirect_url(self, *args, **kwargs):
        return reverse('users:profile')

learning_log/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <title>{% block title %}{{ title }}{% endblock %} | Live Journal</title>
</head>
<body>
    {% include "navbar_snippet.html" %}

    <div class="container">
        {% url 'learning_logs:index' as index %}
        {% if request.path != index %}
          <header class="mt-3">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'learning_logs:index' %}">Home</a></li>
                {% block breadcrumb %}{% endblock %}
                <li class="breadcrumb-item active">{{ title }}</li>
              </ol>
            </nav>
          </header>
        {% endif %}

        {% include "messages_snippet.html" %}

        {% block content %}{% endblock %}
    </div>

    {% include "footer_snippet.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="{% static 'plugins/ckeditor/ckeditor.js' %}"></script>
    <script src="{% static 'plugins/ckfinder/ckfinder.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

learning_log/templates/footer_snippet.html
<footer class="container mt-3">
    <p>&copy; 2020 Live Journal</p>
</footer>

learning_log/templates/messages_snippet.html
<div class="mt-3">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                <strong>{{ message.tags|capfirst }}!</strong> {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}      
    {% endif %}
</div>

learning_log/templates/navbar_snippet.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'learning_logs:index' %}" id="header-font">Live Journal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:newest' %}">New</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:top' %}">Top</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:entries' %}">All Articles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:tags' %}">Tags</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbardrop" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username|title }}</a>
                    <div class="dropdown-menu" aria-labelledby="navbardrop">
                        <a class="dropdown-item" href="{% url 'learning_logs:entry_create' %}">Add article</a>
                        <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                </li>
            {% endif %}
        </ul>

        <form class="d-flex" action="{% url 'learning_logs:entries' %}" method="get">
          <input class="form-control me-2" name="q" type="text" value="{{ q|default:'' }}" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>                 
    </div>
  </div>
</nav>